apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/springmuffin/argo-demo.git  # Change to your repo
    targetRevision: HEAD
    path: .  # Assuming k8s.yaml is at the root of the repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
